export const TaskTypeEnum = {
	BreadthFirstSearch : 0,
	BestFirstSearch: 1,
	Dijkstra: 2,
	AStar: 3,
	WeightRadiusDiameterPower: 4,
	GraphIsomorphism: 5,
	GraphConnectivity: 6,
	GraphAddition: 7,
	GraphPlanarity: 8,
	RecoverGraphFromVector: 9,
	ExtremeGraphs: 10,
	MinimumSpanningTree: 11,
	CycleProblem: 12,
	ColoringGraph: 13,
	TheProblemOfWeddings: 14,
	SupplementTwoComplex: 15,
	RecoveryOfTwoComplexVector: 16,
	ExtremeTwoComplex: 17,
	TravelingSalesmanTask: 18,
	TheEffectivenessOfPathFindingAlgorithms: 19,
};
